### ISSUE TITLE
in relation to the execution of

### ISSUE THREAD

**Issue by hyunwoossong1** [ddoeppner/one-record-server-first-steps#1]
Hello
I followed the guide you gave me, and I followed it with talken_endpoint or client_id and so on..
Where can I find out _id, etc.?

**Comment by ddoeppner** [comment]
Hello @hyunwoossong1,
thank you for your question.

It depends on your setup. 
Usually client_id, client_secret, token_url, etc. should be provided by your IdP / token issuer.

For example, if you use the provided docker-compose setup with Keycloak, you can use the following:

**Access Token URL:** http://localhost:8989/realms/neone/protocol/openid-connect/token
**grant_type:** client_credentials
**client_id:** neone-client
**client_secret:** lx7ThS5aYggdsMm42BP3wMrVqKm9WpNY

**Request:**
```http
POST http://localhost:8989/realms/neone/protocol/openid-connect/token
grant_type: "client_credentials"
client_id: "neone-client"
client_secret: "lx7ThS5aYggdsMm42BP3wMrVqKm9WpNY"
```

**Response:**
```json
{
  "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJLS1BFU0Y5OWtwX213R1RBTUgwT1VEZlZOS2NjV3QxWS12bHNWaURhMng4In0.eyJleHAiOjE3MTIxNjU1OTQsImlhdCI6MTcxMjEyOTU5NCwianRpIjoiM2M2ZGQyN2ItYWJiNy00ZDEyLTg1YjMtMTliNzQzMDQ1MDU5IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4OTg5L3JlYWxtcy9uZW9uZSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiIwYWU4OThmMy1kMjQ4LTRlYWMtODY4MS1iMDM4MWM4MmQ2YzAiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJuZW9uZS1jbGllbnQiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwiZGVmYXVsdC1yb2xlcy1uZW9uZSIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwiY2xpZW50SG9zdCI6IjE5Mi4xNjguNjUuMSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibG9naXN0aWNzX2FnZW50X3VyaSI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9sb2dpc3RpY3Mtb2JqZWN0cy9fZGF0YS1ob2xkZXIiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzZXJ2aWNlLWFjY291bnQtbmVvbmUtY2xpZW50IiwiY2xpZW50QWRkcmVzcyI6IjE5Mi4xNjguNjUuMSIsImNsaWVudF9pZCI6Im5lb25lLWNsaWVudCJ9.ba4Qh1ILtKrf2rgjP2lYcbGBbpm0w-BDCDQkaT11TXV_arnDelL9BOiqS_kQx2atMV6xfdjoiiD_wqgsAhnaLp9tZa0gn5sSkHrm7LTATEUFa9GzXIiWdHlcMvTnFEI5kwTtWTxuRVN90OFHL_EaPhHkXzrsFVuvx2ZqdBRVNzMTVBKTNmPEMVlMWiU8LQmHeukDbkhk1mM1FkGXA2b2NvrZJatpt_5bglbjcaJAqgqzIC2GWNwrjlhevTJg-WBOTgpld8zcAtlwaOSLTAmqtmNjwk5sPq0AtcE0Yhrtvygq04EDZKUQCa8x4Dv_SkxbZqh57NDxC4VxcB3RRgzA1w",
  "expires_in": 36000,
  "refresh_expires_in": 0,
  "token_type": "Bearer",
  "not-before-policy": 0,
  "scope": "profile email"
}
```

**Comment by hyunwoossong1** [comment]
Thanks you.  
When I filled in the value with the information that guided me as it was, the following response occurred.

client_secret and client_id value fixed?? like a neone-client and lx7ThS5aYggdsMm42BP3wMrVqKm9WpNY

I don't know where those values come from..

![image](https://github.com/ddoeppner/one-record-server-first-steps/assets/165880466/b0772dd0-784d-461a-9477-e73fbfd9324a)

There are many other questions.
What's the difference between this project and NE-ONE right now??

**Comment by ddoeppner** [comment]
Your response seems to be correct. 

The **client_id** and **client_secret** are preconfigured in [neone-realms.json](https://github.com/ddoeppner/one-record-server-first-steps/blob/2028f5f4cca2f10662970bab8ada57002f9d5853/docker-compose/keycloak/neone-realms.json) and are imported when the Keycloak container is started.

You can change the values (a) in neone-realms.json or (b) in the Keycloak admin panel. 
For (b), I recommend consulting the [Keycloak](https://www.keycloak.org/docs/latest/authorization_services/index.html) documentation.

This project is a tutorial for getting started with ONE Record, created for the IATA ONE Record Hackathon 2023 in Seeheim. To make it easier for the user, it contains a pre-configured ne-one server environment that can be easily started and used locally.

**Comment by hyunwoossong1** [comment]
I appreciate your kind words. 
I found the relevant information in the docker-compose folder.
![image](https://github.com/ddoeppner/one-record-server-first-steps/assets/165880466/5705ad15-e239-4682-acb5-e2b76cbc346a)

We are proceeding to the next step (Get Server Information),  
It seems like you followed the guide, received the access token, and inserted it. Now, you're questioning whether the server URL should remain as "localhost:8080" as obtained from Git. "An error occurred as shown in the image below when using localhost:8080."

![image](https://github.com/ddoeppner/one-record-server-first-steps/assets/165880466/d3d1a566-b578-4b34-b725-c8a9a62363e6)

Just for reference, Docker is running.

![image](https://github.com/ddoeppner/one-record-server-first-steps/assets/165880466/f777876b-0c0e-4073-93d5-3e8f364f7e97)

**Comment by ddoeppner** [comment]
The correct URL is
**http://localhost:8080** not `https://<locahost:8080>`

- No angle brackets < > 
- http instead of https

**Comment by hyunwoossong1** [comment]
Thanks you

If Forwarder or CCS claims to set up a OneRecord server, 
Is it sufficient to just utilize the program uploaded on GitHub like a one-record-server-first-steps or ne-one ??

**Comment by ddoeppner** [comment]
yes, the [ne-one sever](https://git.openlogisticsfoundation.org/wg-digitalaircargo/ne-one) package is definitely built for this use case, i.e. representing a Forwarder or CSS in ONE Record ecosystem and publish data.

You can use this [one-record-server-first-steps](https://github.com/ddoeppner/one-record-server-first-steps) tutorial as a starting point to familiarize yourself with the ONE Record API, the ONE Record data model and also with the ne-one software.

However, please note that the setup provided in this tutorial is not production-ready, you will need to configure ne-one for your specific environment and requirements.

**Comment by hyunwoossong1** [comment]
ne-one software is the concept of a server, and one-record-server-java program is a client ??
Forwarder and ccs need both server and client, right?

![image](https://github.com/ddoeppner/one-record-server-first-steps/assets/165880466/da8362b0-75c5-43ce-8259-2f9a8837fc5d)

**Comment by ddoeppner** [comment]
[ne-one server](https://git.openlogisticsfoundation.org/wg-digitalaircargo/ne-one) is a server-side implementation of the latest [ONE Record API](https://iata-cargo.github.io/ONE-Record/) specification

The ONE Record Server Java Sandbox is also a server implementation of the ONE Record API specification; however, it is based on an outdated version.

If you need a client to communicate with your ONE Record Server, you need to implement one. The ONE Record Server API is based on standard REST design principles, so any REST-based client implementation should work.

**Comment by ddoeppner** [comment]
I am closing this topic for now. Thank you for the discussion. If you have any further questions, please reopen the issue or create a new one.
