### ISSUE TITLE
NE-ONE server error related

### ISSUE THREAD

**Issue by chanyang0457** [ddoeppner/one-record-server-first-steps#2]
I'm trying to run the ne-one server.  But the following error occurs

WARN: OIDC server is not available at the 'http://localhost:8989/realms/neone' URL. Please make sure it is correct. Note it has to end with a realm value if you work with Keycloak, for example: 'https://localhost:8180/auth/realms/quarkus'

http://localhost:8989/realms/neone The address is accessible.

![image](https://github.com/ddoeppner/one-record-server-first-steps/assets/60687161/972e148b-7237-43ba-bd01-5c816c4665fc)

Can I get some advice?

**Comment by ddoeppner** [comment]
Hi @chanyang0457,

please provide more details on your setup.

How did you start ne-one server? 
How did you start Keycloak?

If you used docker, a screenshot of your running containers would be helpful.

**Comment by chanyang0457** [comment]
Hi @ddoeppner,

I even progressed to Keycloak compose.

![image](https://github.com/ddoeppner/one-record-server-first-steps/assets/60687161/71fb833b-741f-49df-8845-dd405d9a1e12)

An error occurs in docker-compose-neone-1 as shown below.

![image](https://github.com/ddoeppner/one-record-server-first-steps/assets/60687161/afd89b80-13cb-4a1e-b709-07192a4eac0f)

http://localhost:8989/realms/neone can be accessed as follows.

![image](https://github.com/ddoeppner/one-record-server-first-steps/assets/60687161/fba0beb1-8fee-4d14-9d38-cb0a3b4202f8)


Can I get some advice?

**Comment by ddoeppner** [comment]
Hello @chanyang0457 
it seems that you used the Docker Compose files from the OLF ne-one repository, not the Docker Compose files from this repository. 
see https://github.com/ddoeppner/one-record-server-first-steps/tree/main/docker-compose

My guess is that the Docker containers are not running on the same network. If this is the case, Keycloak (as a separate container in addition to the ne-one container) is not accessible via localhost, but via the container name in the network.

For example in https://github.com/ddoeppner/one-record-server-first-steps/blob/main/docker-compose/docker-compose.yml
Keycloak is accessible from the other containers via keycloak as the host name and therefore `QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL=http://keycloak:8989/realms/neone` is configured.

I suggest taking look at the docker networking documentatiokn to get a better understanding how container in docker / docker compose can communicate with each other. > https://docs.docker.com/compose/networking/

**Comment by ddoeppner** [comment]
I am closing this issue for now. Thank you for the discussion. If you have any further questions, please reopen the issue or create a new one.
